sudo: false
language: node_js
node_js:
  - '11'
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: npm
  email: 000scorpio000@gmail.com
  api_key:
    secure: hfh9bhO8X0mOybquvHXB2TSxNE4lS9fU5bNNCcbYkQhUmdZaYdxmRGLCzK2dOXajd+Oh9WPDQ6ef/gvDxXJvKyV6x6FlLuqMJ0wyU2Hc2HG2KmUNjEofpS0QCLyPbP5YA0DaVcEMPdDX9B/S/UGLRfByR7aNsgU7awaQQWDVjFp1A1m5hvN8E53sdhQgK54d2iz/frNReq6sOtJza3WpZDVcZ6OgPaL3JTQea6Lq/Ph+tZL4nItoywKrmjNPKmVwtl+wFZM71mynbUhmDDAzug3pK2FiUc/88mycz0stoBjxwoZDI8jLUT/d6UsK6fUBnhQ0hPCk8JozTDK3g7JP7G71FYFkyC0M32OMbHPxgcRPYq2VJ1kznhG2Ohmd0Hu7q6Ampb8ZNLHOUBhFnoa1CSlRuXLRfNEn2mcvNveZIRR7L3gYjjFayPSwDKBExx5EZHwmaaQoKELfekhufDV9FL9NmGmitOA9vLiiN+pPco4eUiwvgnz5HtF5E7WMrDts2HvV+J5m/nxNSMAtt73l4XqA9BZo45G4mW5arb01mZmBTLQGuPlqrZ5fZQzVnRJqwOQUkg1/cR2nCmMfS2K3c2VgwwfdKZhOram5xtyV+FimY2dMP2RWz3jsdwc/vDM7m/GlOzel+sJsHAwbMR037iskwxzRzi4U5+FZ1IE3xdg=
  on:
    tags: true
    branch: master
    node_js: 10
